[package]
name = "include_lua_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2.0.17"
quote = "^1.0"
walkdir = "2.3.3"

[lib]
proc-macro = true