mod fmod;
use std::{collections::HashMap, io::Write};
use std::io::{Cursor, Read};

pub trait FmodResultTrait {
    fn print(&self);
    fn as_result(&self) -> Result<(), String>;
}

/// add util fns for fmod result code
impl FmodResultTrait for fmod::FMOD_RESULT {
    fn print(&self) {
        println!("{}", format_fmod_result(*self));
    }

    #[inline]
    fn as_result(&self) -> Result<(), String> {
        match *self {
            0=> Ok(()),
            n=> Err(format_fmod_result(n)),
        }
    }
}

/// convert fmod error code to human string
pub fn format_fmod_result(result: fmod::FMOD_RESULT)-> String {
    match result {  
        0 => "FMOD_RESULT_FMOD_OK", 
        1 => "FMOD_RESULT_FMOD_ERR_ALREADYLOCKED",
        2 => "FMOD_RESULT_FMOD_ERR_BADCOMMAND",
        3 => "FMOD_RESULT_FMOD_ERR_CDDA_DRIVERS",
        4 => "FMOD_RESULT_FMOD_ERR_CDDA_INIT",
        5 => "FMOD_RESULT_FMOD_ERR_CDDA_INVALID_DEVICE",
        6 => "FMOD_RESULT_FMOD_ERR_CDDA_NOAUDIO",
        7 => "FMOD_RESULT_FMOD_ERR_CDDA_NODEVICES",
        8 => "FMOD_RESULT_FMOD_ERR_CDDA_NODISC",
        9 => "FMOD_RESULT_FMOD_ERR_CDDA_READ",
        10 => "FMOD_RESULT_FMOD_ERR_CHANNEL_ALLOC",
        11 => "FMOD_RESULT_FMOD_ERR_CHANNEL_STOLEN",
        12 => "FMOD_RESULT_FMOD_ERR_COM",
        13 => "FMOD_RESULT_FMOD_ERR_DMA",
        14 => "FMOD_RESULT_FMOD_ERR_DSP_CONNECTION",
        15 => "FMOD_RESULT_FMOD_ERR_DSP_FORMAT",
        16 => "FMOD_RESULT_FMOD_ERR_DSP_NOTFOUND",
        17 => "FMOD_RESULT_FMOD_ERR_DSP_RUNNING",
        18 => "FMOD_RESULT_FMOD_ERR_DSP_TOOMANYCONNECTIONS",
        19 => "FMOD_RESULT_FMOD_ERR_FILE_BAD",
        20 => "FMOD_RESULT_FMOD_ERR_FILE_COULDNOTSEEK",
        21 => "FMOD_RESULT_FMOD_ERR_FILE_DISKEJECTED",
        22 => "FMOD_RESULT_FMOD_ERR_FILE_EOF",
        23 => "FMOD_RESULT_FMOD_ERR_FILE_NOTFOUND",
        24 => "FMOD_RESULT_FMOD_ERR_FILE_UNWANTED",
        25 => "FMOD_RESULT_FMOD_ERR_FORMAT",
        26 => "FMOD_RESULT_FMOD_ERR_HTTP",
        27 => "FMOD_RESULT_FMOD_ERR_HTTP_ACCESS",
        28 => "FMOD_RESULT_FMOD_ERR_HTTP_PROXY_AUTH",
        29 => "FMOD_RESULT_FMOD_ERR_HTTP_SERVER_ERROR",
        30 => "FMOD_RESULT_FMOD_ERR_HTTP_TIMEOUT",
        31 => "FMOD_RESULT_FMOD_ERR_INITIALIZATION",
        32 => "FMOD_RESULT_FMOD_ERR_INITIALIZED",
        33 => "FMOD_RESULT_FMOD_ERR_INTERNAL",
        34 => "FMOD_RESULT_FMOD_ERR_INVALID_ADDRESS",
        35 => "FMOD_RESULT_FMOD_ERR_INVALID_FLOAT",
        36 => "FMOD_RESULT_FMOD_ERR_INVALID_HANDLE",
        37 => "FMOD_RESULT_FMOD_ERR_INVALID_PARAM",
        38 => "FMOD_RESULT_FMOD_ERR_INVALID_POSITION",
        39 => "FMOD_RESULT_FMOD_ERR_INVALID_SPEAKER",
        40 => "FMOD_RESULT_FMOD_ERR_INVALID_SYNCPOINT",
        41 => "FMOD_RESULT_FMOD_ERR_INVALID_VECTOR",
        42 => "FMOD_RESULT_FMOD_ERR_MAXAUDIBLE",
        43 => "FMOD_RESULT_FMOD_ERR_MEMORY",
        44 => "FMOD_RESULT_FMOD_ERR_MEMORY_CANTPOINT",
        45 => "FMOD_RESULT_FMOD_ERR_MEMORY_SRAM",
        46 => "FMOD_RESULT_FMOD_ERR_NEEDS2D",
        47 => "FMOD_RESULT_FMOD_ERR_NEEDS3D",
        48 => "FMOD_RESULT_FMOD_ERR_NEEDSHARDWARE",
        49 => "FMOD_RESULT_FMOD_ERR_NEEDSSOFTWARE",
        50 => "FMOD_RESULT_FMOD_ERR_NET_CONNECT",
        51 => "FMOD_RESULT_FMOD_ERR_NET_SOCKET_ERROR",
        52 => "FMOD_RESULT_FMOD_ERR_NET_URL",
        53 => "FMOD_RESULT_FMOD_ERR_NET_WOULD_BLOCK",
        54 => "FMOD_RESULT_FMOD_ERR_NOTREADY",
        55 => "FMOD_RESULT_FMOD_ERR_OUTPUT_ALLOCATED",
        56 => "FMOD_RESULT_FMOD_ERR_OUTPUT_CREATEBUFFER",
        57 => "FMOD_RESULT_FMOD_ERR_OUTPUT_DRIVERCALL",
        58 => "FMOD_RESULT_FMOD_ERR_OUTPUT_ENUMERATION",
        59 => "FMOD_RESULT_FMOD_ERR_OUTPUT_FORMAT",
        60 => "FMOD_RESULT_FMOD_ERR_OUTPUT_INIT",
        61 => "FMOD_RESULT_FMOD_ERR_OUTPUT_NOHARDWARE",
        62 => "FMOD_RESULT_FMOD_ERR_OUTPUT_NOSOFTWARE",
        63 => "FMOD_RESULT_FMOD_ERR_PAN",
        64 => "FMOD_RESULT_FMOD_ERR_PLUGIN",
        65 => "FMOD_RESULT_FMOD_ERR_PLUGIN_INSTANCES",
        66 => "FMOD_RESULT_FMOD_ERR_PLUGIN_MISSING",
        67 => "FMOD_RESULT_FMOD_ERR_PLUGIN_RESOURCE",
        68 => "FMOD_RESULT_FMOD_ERR_PRELOADED",
        69 => "FMOD_RESULT_FMOD_ERR_PROGRAMMERSOUND",
        70 => "FMOD_RESULT_FMOD_ERR_RECORD",
        71 => "FMOD_RESULT_FMOD_ERR_REVERB_INSTANCE",
        72 => "FMOD_RESULT_FMOD_ERR_SUBSOUND_ALLOCATED",
        73 => "FMOD_RESULT_FMOD_ERR_SUBSOUND_CANTMOVE",
        74 => "FMOD_RESULT_FMOD_ERR_SUBSOUND_MODE",
        75 => "FMOD_RESULT_FMOD_ERR_SUBSOUNDS",
        76 => "FMOD_RESULT_FMOD_ERR_TAGNOTFOUND",
        77 => "FMOD_RESULT_FMOD_ERR_TOOMANYCHANNELS",
        78 => "FMOD_RESULT_FMOD_ERR_UNIMPLEMENTED",
        79 => "FMOD_RESULT_FMOD_ERR_UNINITIALIZED",
        80 => "FMOD_RESULT_FMOD_ERR_UNSUPPORTED",
        81 => "FMOD_RESULT_FMOD_ERR_UPDATE",
        82 => "FMOD_RESULT_FMOD_ERR_VERSION",
        83 => "FMOD_RESULT_FMOD_ERR_EVENT_FAILED",
        84 => "FMOD_RESULT_FMOD_ERR_EVENT_INFOONLY",
        85 => "FMOD_RESULT_FMOD_ERR_EVENT_INTERNAL",
        86 => "FMOD_RESULT_FMOD_ERR_EVENT_MAXSTREAMS",
        87 => "FMOD_RESULT_FMOD_ERR_EVENT_MISMATCH",
        88 => "FMOD_RESULT_FMOD_ERR_EVENT_NAMECONFLICT",
        89 => "FMOD_RESULT_FMOD_ERR_EVENT_NOTFOUND",
        90 => "FMOD_RESULT_FMOD_ERR_EVENT_NEEDSSIMPLE",
        91 => "FMOD_RESULT_FMOD_ERR_EVENT_GUIDCONFLICT",
        92 => "FMOD_RESULT_FMOD_ERR_EVENT_ALREADY_LOADED",
        93 => "FMOD_RESULT_FMOD_ERR_MUSIC_UNINITIALIZED",
        94 => "FMOD_RESULT_FMOD_ERR_MUSIC_NOTFOUND",
        95 => "FMOD_RESULT_FMOD_ERR_MUSIC_NOCALLBACK",
        _ => return format!("FMOD_RESULT_FMOD_ERR_UNKNOWN: {}", result), // String
    }.to_string()
}